import Head from "next/head";
import styles from "../styles/Product.module.css";
import { useEffect, useState } from "react";

function Product() {
    const [initialData, SetData] = useState([])

  useEffect(() => {
    store()
  }, [])

  const store = async () => {
    try {
      const response = await fetch("https://fakestoreapi.com/products")
      const jsonData = await response.json()
      SetData(jsonData)
    } catch (err) {
      document.writeln(err+"please try again..")
    }
  };
  store()

  return (
    <>
      <Head>
        <title>ShopEase | Shoping done right</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        {initialData.map((values) => {
          return (
            <>
              <div className={styles.outerBox}>
                <div className="content">
                  <h4 className={styles.productName}>
                    {values.title.slice(0, 36)}..
                  </h4>
                  <p className={styles.para}>
                    <span className={styles.label}>CATEGORY: </span>
                    {values.category}
                  </p>
                  <p className={styles.para}>
                    {values.description.slice(0, 155)}..
                  </p>
                  <p className={styles.price}>
                    <span className={styles.price}>PRICE: </span>
                    ${values.price}
                  </p>
                </div>
                <img
                  className={styles.img}
                  src={values.image}
                  alt="product-image"
                />
                
               
              </div>
            </>
          );
        })}
      </div>
    </>
  );
}

export default Product